# Generated by Django 2.0.2 on 2018-02-20 20:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('message', models.TextField(max_length=400)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'News',
                'verbose_name_plural': 'News',
                'ordering': ('created',),
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(blank=True, max_length=100)),
                ('telegram', models.CharField(max_length=100)),
                ('skype', models.CharField(max_length=100)),
                ('hipchat', models.CharField(max_length=100)),
                ('phone', models.IntegerField()),
                ('about', models.TextField(max_length=400)),
                ('photo', models.ImageField(blank=True, upload_to='static')),
                ('agent', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('username', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profile',
                'ordering': ('created',),
            },
        ),
        migrations.CreateModel(
            name='Reader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_date', models.DateTimeField(auto_now_add=True)),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.News')),
                ('reader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Profile')),
            ],
            options={
                'verbose_name': 'Reader',
                'verbose_name_plural': 'Reader',
                'ordering': ('read_date',),
            },
        ),
        migrations.AddField(
            model_name='news',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='news_author', to='dashboard.Profile'),
        ),
        migrations.AddField(
            model_name='news',
            name='readers',
            field=models.ManyToManyField(related_name='news_reader', through='dashboard.Reader', to='dashboard.Profile'),
        ),
    ]
