# Generated by Django 2.0.2 on 2018-02-20 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_system'),
    ]

    operations = [
        migrations.AddField(
            model_name='system',
            name='read',
            field=models.BooleanField(default=False),
        ),
    ]
