# Generated by Django 2.0.2 on 2018-02-20 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_system_read'),
    ]

    operations = [
        migrations.AlterField(
            model_name='system',
            name='url',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
