# Generated by Django 2.0.2 on 2018-02-20 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_auto_20180220_1856'),
    ]

    operations = [
        migrations.RenameField(
            model_name='system',
            old_name='url',
            new_name='link',
        ),
    ]
