# Generated by Django 2.0.2 on 2018-02-22 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_auto_20180222_1534'),
    ]

    operations = [
        migrations.RenameField(
            model_name='change',
            old_name='unavailability',
            new_name='impact',
        ),
    ]
